
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';

// Precache all assets generated by your build process
// @ts-ignore
precacheAndRoute(self.__WB_MANIFEST);

// Cache Google Fonts
registerRoute(
  ({url}) => url.origin === 'https://fonts.googleapis.com' || 
             url.origin === 'https://fonts.gstatic.com',
  new StaleWhileRevalidate({
    cacheName: 'google-fonts',
  })
);

// Cache CDN resources (like from cdn.gpteng.co)
registerRoute(
  ({url}) => url.origin === 'https://cdn.gpteng.co',
  new StaleWhileRevalidate({
    cacheName: 'cdn-resources',
  })
);

// Default cache strategy for everything else
registerRoute(
  () => true,
  new StaleWhileRevalidate({
    cacheName: 'default-cache',
  })
);

// Skip the waiting phase to make updates apply immediately
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    // @ts-ignore
    self.skipWaiting();
  }
});
